#!/usr/bin/env python3
# build-v3-proto.py — wall-thickness v3 prototype, PASS 1.
# chat (data-aligned) -> report opens FULL-BLEED with a "generated by Deckhand"
# bar -> keyframed scroll (section labels + dwell pauses) with a spotlight on the
# governing result and the plot "drawing in" -> CTA (unwired, #409/#431).
# Emits demo-wt-v3.html (+ .dur). Render: SLUG=wt-v3 bash render-anim.sh
import json, pathlib
from PIL import Image
ROOT = pathlib.Path(__file__).parent
IMG = "file:///tmp/wt-report.png"
iw, ih = Image.open("/tmp/wt-report.png").size
DOCH = round(ih * 1200 / iw)            # displayed report height
REPORT_FILE = "wall_thickness_quickcheck_report.html"

# --- chat aligned to the REAL report (results.yaml): 300 bar design,
#     pressure_containment governs (U=0.971, tight), SCH 80; without -> SCH 140 (propagation)
spec = {
 "channel": {"name": "Subsea, Pipelines & Integrity", "tags": "🛢️ pipeline · structural · integrity"},
 "title": {"big": "Pipeline wall thickness, answered in chat",
           "desc": "Ask in plain English. Deckhand asks for what it needs, runs the calculation, and sends back a report you can keep."},
 "turns": [
  {"side":"me","time":"09:34","hold":900,"html":"I've got a 12-inch export line going into 1500&nbsp;m in the Gulf and need a quick wall-thickness screen before we lock the line pipe order. Can you check it across the codes?"},
  {"side":"bot","typing":True,"hold":1200},
  {"side":"bot","time":"09:34","hold":4200,"html":"Happy to screen it — two things drive the wall, so let me get them straight first:<ul><li><b>Pressure basis</b> — is the rating you'll give me the <i>operating</i> or the <i>design</i> pressure? I size containment on design.</li><li><b>Buckle arrestors</b> — running them or not? Without arrestors I carry the full propagation-buckle wall (much heavier pipe); with them I only need the collapse wall between them.</li></ul>Then the basics: line size, steel grade, water depth.<br><span class='note'>I screen carbon-steel line pipe against DNV-ST-F101 and API&nbsp;RP&nbsp;1111. Flexibles and risers are a different check.</span>"},
  {"side":"me","time":"09:36","hold":4000,"file":{"name":"line_datasheet.csv","size":"1.4 KB"},"html":"12.75-inch OD, grade X65, 1500&nbsp;m water depth. The <b>300&nbsp;bar</b> I'm giving you is the <b>design</b> pressure, and we're planning <b>buckle arrestors</b>. Datasheet attached — 3&nbsp;mm corrosion allowance in there too."},
  {"side":"bot","typing":True,"hold":1200},
  {"side":"bot","time":"09:36","hold":4400,"html":"Got it — design pressure 300&nbsp;bar, X65, 1500&nbsp;m, with buckle arrestors. Basis I'll use: containment at design pressure, and collapse &amp; propagation for the empty line at full depth. Codes: DNV-ST-F101 and API&nbsp;RP&nbsp;1111, then I pick the next standard schedule above the minimum. Running it now…"},
  {"side":"bot","wide":True,"time":"09:37","hold":3000,"file":{"name":"wall_thickness_quickcheck_report","size":"inputs · method · results","deliver":True},"html":"Here's the screen, with and without arrestors so you can see the trade:<table><tr><th>Case</th><th>Governing check</th><th>Min wall</th><th>Selected</th><th>Margin</th></tr><tr><td>With arrestors</td><td>DNV-ST-F101 pressure-containment</td><td>17.08&nbsp;mm</td><td>SCH&nbsp;80 · 17.48&nbsp;mm</td><td class='verdict'>✅ tight · U 0.97</td></tr><tr><td>Without arrestors</td><td>DNV-ST-F101 propagation</td><td>25.41&nbsp;mm</td><td>SCH&nbsp;140 · 28.58&nbsp;mm</td><td class='verdict'>✅ 28%</td></tr></table><span class='note'>With the arrestors you planned, SCH&nbsp;80 carries it — but it's <b>tight</b>: pressure containment runs at 97% utilisation. Drop the arrestors and propagation governs → SCH&nbsp;140 line pipe.</span>"}
 ],
 "closing": {"headline":"Pipeline wall thickness: min WT across codes + capacity margin.",
             "tryThis":"Min wall thickness for a 12-inch X65 line at 250 bar?",
             "route":"Subsea, Pipelines & Integrity"}
}

# --- report-scroll keyframes (displayed doc coords; bar is 40px) ---
# stop = {y: scrollTop target, dwell ms, label, optional spot[x,y,w,h], optional plot[x,y,w,h]}
maxS = DOCH - (675 - 40 - 42)   # visible report area = frame - top bar - footer
STOPS = [
  {"y":0,    "dwell":1200, "label":"Inputs & assumptions"},
  {"y":520,  "dwell":1800, "label":"Results — wall thickness", "spot":[34,660,1128,44]},
  {"y":980,  "dwell":700,  "label":"Buckle-arrestor sizing"},
  {"y":1430, "dwell":2200, "label":"Utilisation plot", "plot":[0,1430,1200,745]},
  {"y":maxS, "dwell":1500, "label":"Design-basis caveat"},
]
SEG = 1900   # scroll time between stops

LOGOMARK = '<svg class="mk"><use href="#dhmark"/></svg>'
SYMBOL = '<svg width="0" height="0" style="position:absolute" aria-hidden="true"><defs><symbol id="dhmark" viewBox="-8 2 246 216"><path d="M0 10h130c58 0 100 42 100 100s-42 100-100 100H0z" fill="#0B3D91"/><path d="M38 72c20-32 64-32 84 0v76c-20 32-64 32-84 0z" fill="#2BB2A6" opacity=".9"/><path d="M30 140c12 16 31 26 55 26s43-10 55-26" fill="none" stroke="#6FE8D4" stroke-width="6" stroke-linecap="round"/><path d="M30 110c12 16 31 26 55 26s43-10 55-26" fill="none" stroke="#12A6B0" stroke-width="6" stroke-linecap="round" opacity=".7"/><path d="M30 80c12 16 31 26 55 26s43-10 55-26" fill="none" stroke="#0B3D91" stroke-width="6" stroke-linecap="round" opacity=".45"/><rect x="18" y="48" width="20" height="120" fill="#0B3D91"/><path d="M16 52c0-6.6 5.4-12 12-12s12 5.4 12 12-5.4 12-12 12-12-5.4-12-12z" fill="#0B3D91"/></symbol></defs></svg>'

ENGINE = r"""<!doctype html><html lang="en"><head><meta charset="utf-8"><style>
:root{--bg:#0b1220;--ink:#e8eef9;--muted:#90a0bd;--accent:#4cc2ff;--accent2:#7af0c0;--user:#2b6fed;--bot:#16223e;--ok:#3ad29f;--line:#22304f;}
*{box-sizing:border-box;margin:0;padding:0;font-family:-apple-system,"Segoe UI",Roboto,Helvetica,Arial,sans-serif}
html,body{width:1200px;height:675px;background:#cdd8e3;overflow:hidden}
#win{position:absolute;top:0;left:0;width:1200px;height:675px;transform:scale(.953);transform-origin:50% 50%;border-radius:22px;overflow:hidden;box-shadow:0 18px 55px rgba(15,35,65,.3)}
.stage{position:relative;width:1200px;height:675px;display:flex;flex-direction:column;background:radial-gradient(circle at 20% 14%,rgba(255,255,255,.05) 0 7px,transparent 8px),radial-gradient(circle at 74% 30%,rgba(0,0,0,.022) 0 9px,transparent 10px),linear-gradient(180deg,#c6d3df,#cdd8e3);background-size:150px 150px,190px 190px,100% 100%}
.chead{display:flex;align-items:center;gap:13px;padding:13px 24px;background:#527da5;z-index:2;box-shadow:0 1px 3px rgba(0,0,0,.18)}
.avatar{width:42px;height:42px;border-radius:50%;background:#eaf4ff;border:1px solid #cfe4f5;display:flex;align-items:center;justify-content:center;overflow:hidden}
.chead .nm{font-weight:700;font-size:17px;color:#fff}.chead .st{font-size:12.5px;color:#cfe0f2}
.chead .right{margin-left:auto;font-size:12.5px;color:#dbe8f5;border:1px solid rgba(255,255,255,.3);border-radius:999px;padding:5px 12px}
.msgs{flex:1;min-height:0;display:flex;flex-direction:column;justify-content:flex-end;gap:12px;padding:22px 120px 66px 28px;overflow:hidden}
.turn{display:flex;flex-direction:column;max-width:74%;overflow:hidden}.turn.me{align-self:flex-end;align-items:flex-end}.turn.bot{align-self:flex-start;align-items:flex-start}.turn.wide{max-width:84%}
.who{font-size:11.5px;color:#6d8298;margin:0 6px 3px}
.bubble{padding:11px 15px;border-radius:16px;font-size:15px;line-height:1.5;color:#0e1621;box-shadow:0 1px 2px rgba(20,40,70,.16)}
.me .bubble{background:#e7fcd4;border-bottom-right-radius:5px}.bot .bubble{background:#fff;border:1px solid #e2e9f0;border-bottom-left-radius:5px}
.bubble ul{margin:7px 0 2px;padding-left:18px}.bubble li{margin:3px 0}.bubble .note{display:block;margin-top:9px;font-size:13px;color:#3a8a5a;border-top:1px solid #eef2ee;padding-top:7px}
.time{font-size:10.5px;color:#8aa0b0;margin:3px 8px 0}
.file{margin-top:10px;display:inline-flex;align-items:center;gap:9px;background:#f3f7fb;border:1px solid #e2e9f0;border-radius:10px;padding:8px 12px;font-size:13px}
.file .ic{width:26px;height:26px;border-radius:7px;background:#5aa7e6;color:#fff;display:flex;align-items:center;justify-content:center}
.file .fn{font-weight:600;color:#15324a}.file .sz{color:#7e96a8;font-size:11.5px}.file.deliver{border-color:#9fcdeb;background:#eef6fc}
.typing{display:inline-flex;align-items:center;gap:9px;color:#7e93a8;font-size:14px}.pulse{display:inline-flex;gap:4px}.pulse i{width:7px;height:7px;border-radius:50%;background:#9fb3c4}
table{border-collapse:collapse;width:100%;margin-top:7px;font-size:13.5px}th,td{text-align:left;padding:6px 10px;border-bottom:1px solid #e6edf3}
th{color:#789;font-weight:600;font-size:11px;text-transform:uppercase;letter-spacing:.5px}.verdict{color:#1b9e4b;font-weight:700;white-space:nowrap}
.overlay{position:absolute;inset:0;display:flex;flex-direction:column;align-items:center;justify-content:center;text-align:center;padding:56px;color:#fff;background:radial-gradient(1300px 700px at 50% 26%,#2570e6 0%,#134fb0 45%,#0a2c66 100%);z-index:9}
.logo-lg{width:80px;height:80px;border-radius:20px;background:#eaf4ff;border:1px solid #cfe4f5;display:flex;align-items:center;justify-content:center;margin-bottom:24px}
.big{font-size:42px;font-weight:800;letter-spacing:.2px;max-width:1000px;line-height:1.14}
.sub{font-size:21px;color:#bfe6ff;margin-top:14px;font-weight:600}.desc{font-size:17px;color:#d3e2f5;margin-top:18px;max-width:780px;line-height:1.5}
.try{margin-top:24px;font-size:15px;background:#0f1830;border:1px solid var(--line);border-radius:12px;padding:14px 18px;max-width:780px}.try b{color:var(--accent2)}
.join{margin-top:24px;font-size:18px;font-weight:700;color:#06243b;background:linear-gradient(135deg,var(--accent),var(--accent2));padding:14px 28px;border-radius:12px}
.handle{margin-top:12px;font-size:13px;color:var(--muted)}
.avatar .mk{width:30px;height:30px}.logo-lg .mk{width:56px;height:56px}
.cap{position:absolute;left:50%;bottom:20px;transform:translateX(-50%);max-width:680px;text-align:center;background:rgba(8,14,26,.82);border:1px solid var(--line);color:var(--ink);font-size:16px;font-weight:600;padding:9px 20px;border-radius:999px;z-index:8;opacity:0}
.docview{position:absolute;inset:0;background:#fff;overflow:hidden;z-index:5;opacity:0}
#scroller{position:absolute;top:40px;left:0;width:1200px}
#docimg{display:block;width:1200px;height:__DOCH__px}
#plotwipe{position:absolute;background:#fff;display:none}
#spot{position:absolute;border:3px solid #f0b429;border-radius:8px;box-shadow:0 0 0 4px rgba(240,180,41,.22);opacity:0}
.docbar{position:absolute;top:0;left:0;right:0;height:40px;background:#0d1730;border-bottom:1px solid var(--line);display:flex;align-items:center;gap:9px;padding:0 16px;z-index:6;color:#aebbd4;font-size:13px;opacity:0}
.docbar .mk{width:20px;height:20px}.docbar b{color:#eaf4ff;font-weight:600}
.docfoot{position:absolute;left:0;right:0;bottom:0;height:42px;background:#0d1730;border-top:1px solid var(--line);display:flex;align-items:center;justify-content:space-between;padding:0 18px;z-index:6;opacity:0}
.docfoot .lbl{color:#eaf4ff;font-size:14.5px;font-weight:600}
.docfoot .eco{color:#90a0bd;font-size:12.5px}.docfoot .eco b{color:#7af0c0;font-weight:600}
</style></head><body>
__SYMBOL__
<div id="win">
<div class="stage"><div class="chead"><div class="avatar">__MK__</div><div><div class="nm" id="ch-name"></div><div class="st">Open Deck &middot; Deckhand is online</div></div><div class="right" id="ch-tags"></div></div>
<div class="msgs" id="msgs"></div></div>
<div class="cap" id="cap"></div>
<div class="docview" id="docview"><div id="scroller"><img id="docimg" src="__IMG__"><div id="plotwipe"></div><div id="spot"></div></div></div>
<div class="docbar" id="docbar">__MK__ <span>📄 <b>__RFILE__</b> &middot; generated by Deckhand</span></div>
<div class="docfoot" id="docfoot"><span class="lbl" id="footlbl"></span><span class="eco">powered by <b>digitalmodel</b> &middot; aceengineer.com</span></div>
<div class="overlay" id="titlecard"><div class="logo-lg">__MK__</div><div class="big" id="ti-big"></div><div class="sub" id="ti-sub"></div><div class="desc" id="ti-desc"></div></div>
<div class="overlay" id="closecard"><div class="logo-lg">__MK__</div><div class="big" id="cl-big"></div>
<div class="desc">No spreadsheets, no setup. Just ask, in plain English.</div>
<div class="join">Join Deckhand — Start Here &rarr;</div>
<div class="handle">CTA link wired via #409 (onboarding contract #431)</div></div>
</div>
<script>
var SPEC=__SPEC__,STOPS=__STOPS__,SEG=__SEG__,DOCH=__DOCH__;
function el(id){return document.getElementById(id);}
function ease(x){return x<.5?2*x*x:1-Math.pow(-2*x+2,2)/2;}
function clamp(v,a,b){return Math.max(a,Math.min(b,v));}
el('ch-name').textContent=SPEC.channel.name;el('ch-tags').textContent=SPEC.channel.tags;
el('ti-big').textContent=SPEC.title.big;el('ti-sub').textContent='Deckhand · '+SPEC.channel.name;el('ti-desc').textContent=SPEC.title.desc;
el('cl-big').textContent=SPEC.closing.headline;
var msgs=el('msgs');
SPEC.turns.forEach(function(tn,i){var d=document.createElement('div');d.className='turn '+tn.side+(tn.wide?' wide':'');d.id='t-'+i;
 if(tn.typing){d.innerHTML='<div class="who">Deckhand</div><div class="bubble"><span class="typing">typing<span class="pulse"><i></i><i></i><i></i></span></span></div>';}
 else{var who=tn.side==='me'?'You':'Deckhand';var fh='';if(tn.file){var cls=tn.file.deliver?'file deliver':'file';var ic=tn.file.deliver?'📄':'📎';fh='<span class="'+cls+'" style="margin-top:10px"><span class="ic">'+ic+'</span><span><span class="fn">'+tn.file.name+'</span> · <span class="sz">'+tn.file.size+'</span></span></span>';}
  d.innerHTML='<div class="who">'+who+'</div><div class="bubble">'+tn.html+fh+'</div><div class="time">'+(tn.time||'')+'</div>';}
 msgs.appendChild(d);});
var ENTER=520,RFADE=600,TITLE_OUT=2800,CHAT_START=3000,CLOSE_HOLD=3500,DOC_FADE=750;
var turns=SPEC.turns,cursor=CHAT_START;
turns.forEach(function(tn){tn._in=cursor;var h=tn.hold||(tn.typing?1200:3000);if(tn.typing)tn._out=cursor+h;cursor+=h;});
var docIn=cursor+300,t0=docIn+DOC_FADE,cur=t0;
STOPS.forEach(function(s,i){ if(i===0){s._from=cur;s._to=cur;} else {s._from=cur;s._to=cur+SEG;} s._dEnd=s._to+s.dwell; cur=s._dEnd; });
var docOut=cur,closeIn=docOut+RFADE,DURATION=closeIn+CLOSE_HOLD;window.DURATION=DURATION;
var Hh={};
function measure(){turns.forEach(function(tn,i){var e=el('t-'+i);e.style.display='flex';e.style.maxHeight='none';e.style.opacity='0';Hh[i]=e.offsetHeight;});}
function seek(t){
 var tc=el('titlecard');var tfS=TITLE_OUT-RFADE;tc.style.opacity=t<tfS?1:Math.max(0,1-(t-tfS)/RFADE);tc.style.display=t<TITLE_OUT?'flex':'none';
 turns.forEach(function(tn,i){var e=el('t-'+i);var present=t>=tn._in&&(tn._out==null||t<tn._out);if(!present){e.style.display='none';return;}
  e.style.display='flex';var p=ease(clamp((t-tn._in)/ENTER,0,1));e.style.opacity=p;e.style.maxHeight=(Hh[i]*p+(p>=1?60:0))+'px';e.style.transform='translateY('+((1-p)*12)+'px)';});
 var dv=el('docview'),bar=el('docbar'),sc=el('scroller'),wipe=el('plotwipe'),spot=el('spot'),foot=el('docfoot'),fl=el('footlbl');
 if(t>=docIn&&t<closeIn){
   var o=t<docIn+DOC_FADE?(t-docIn)/DOC_FADE:(t>docOut?Math.max(0,1-(t-docOut)/RFADE):1);o=clamp(o,0,1);
   dv.style.opacity=o;bar.style.opacity=o;foot.style.opacity=o;
   // keyframed scroll
   var sy=STOPS[0].y,lbl=STOPS[0].label,active=STOPS[0];
   for(var i=0;i<STOPS.length;i++){var s=STOPS[i];if(t>=s._from){active=s;
     if(i>0&&t<s._to){var p=ease((t-s._from)/SEG);sy=STOPS[i-1].y+(s.y-STOPS[i-1].y)*p;lbl=(p>.55)?s.label:STOPS[i-1].label;}
     else {sy=s.y;lbl=s.label;}}}
   sc.style.transform='translateY('+(-sy)+'px)';
   // spotlight (during the stop that carries one, while dwelling)
   var sp=null;for(var j=0;j<STOPS.length;j++){var s2=STOPS[j];if(s2.spot&&t>=s2._to&&t<s2._dEnd)sp=s2;}
   if(sp){spot.style.left=sp.spot[0]+'px';spot.style.top=sp.spot[1]+'px';spot.style.width=sp.spot[2]+'px';spot.style.height=sp.spot[3]+'px';
     var sf=clamp((t-sp._to)/350,0,1)*clamp((sp._dEnd-t)/350,0,1);spot.style.opacity=clamp(sf,0,1);}else spot.style.opacity=0;
   // plot draws in (during the plot stop)
   var pl=null;for(var k=0;k<STOPS.length;k++){var s3=STOPS[k];if(s3.plot&&t>=s3._from)pl=s3;}
   if(pl){var pp=clamp((t-pl._to)/900,0,1);wipe.style.display='block';wipe.style.top=pl.plot[1]+'px';wipe.style.height=pl.plot[3]+'px';
     wipe.style.left=(pp*pl.plot[2])+'px';wipe.style.width=((1-pp)*pl.plot[2])+'px';}else wipe.style.display='none';
   // footer carries the section label (solid band → always legible)
   fl.textContent=lbl;
 } else {dv.style.opacity=0;bar.style.opacity=0;foot.style.opacity=0;spot.style.opacity=0;wipe.style.display='none';}
 // chat-phase caption only (report labelling now lives in the footer)
 var cap=el('cap');
 if(t>=TITLE_OUT&&t<docIn){cap.textContent='Plain-English chat — Deckhand asks for what it needs, then runs it';cap.style.opacity=1;}
 else cap.style.opacity=0;
 var cc=el('closecard');if(t>=closeIn){cc.style.display='flex';cc.style.opacity=clamp((t-closeIn)/RFADE,0,1);}else{cc.style.display='none';}
}
window.seek=seek;measure();
var _tp=new URLSearchParams(location.search).get('t');seek(_tp!==null?parseInt(_tp,10):0);
</script></body></html>"""

html = (ENGINE.replace("__SYMBOL__", SYMBOL).replace("__MK__", LOGOMARK)
        .replace("__IMG__", IMG).replace("__RFILE__", REPORT_FILE)
        .replace("__DOCH__", str(DOCH)).replace("__SEG__", str(SEG))
        .replace("__STOPS__", json.dumps(STOPS)).replace("__SPEC__", json.dumps(spec, ensure_ascii=False)))
(ROOT/"demo-wt-v3.html").write_text(html)

cur = 3000
for tn in spec["turns"]:
    cur += tn.get("hold", 1200 if tn.get("typing") else 3000)
docIn = cur + 300; t0 = docIn + 750
for i, s in enumerate(STOPS):
    t0 = t0 + (0 if i == 0 else SEG) + s["dwell"]
closeIn = t0 + 600; DUR = closeIn + 3500
(ROOT/"demo-wt-v3.dur").write_text(str(DUR))
print(f"report {iw}x{ih} -> 1200x{DOCH}, maxScroll={maxS}")
print(f"demo-wt-v3.html  DURATION={DUR}ms (~{DUR/1000:.1f}s)")
