#!/usr/bin/env python3
# compose-dynacard.py <out.html> — 2-diagnostic dynamometer-card report.
# Plots two REAL surface cards (load vs rod position) generated by digitalmodel's
# artificial_lift synthetic engine + diagnosed by its DEFAULT classifier:
#   PUMP_TAGGING (plunger tagging) and GAS_LOCK (gas-trapped). Card JSON is produced
#   by /tmp/run_dynacard_mode.py (router-direct). Run from the digitalmodel checkout:
#   uv run --with plotly --with pandas --with pyyaml python compose-dynacard.py <out>
import sys, re, json, pathlib
sys.path.insert(0, "/mnt/local-analysis/.deckhand-compute/digitalmodel/examples/demos/gtm")
import plotly.graph_objects as go
import pandas as pd
from report_template import GTMReportBuilder
TEAL, NAVY, RED = "#2BB2A6", "#0B3D91", "#e53e3e"
# Per-mode card signature phrasing (keeps the composer reusable across faults).
SIG = {"PUMP_TAGGING": "load spike from plunger contact",
       "FLUID_POUND": "incomplete fillage as inflow lags the pump speed",
       "GAS_LOCK": "collapsed card area as gas traps the pump"}

def parse(msg):
    m = msg or ""
    raw = (re.search(r"Classification:\s*([A-Z_]+)", m) or [None, "—"])[1]
    label = raw.replace("_", " ").title()
    cm = re.search(r"Confidence:\s*([\d.]+%)", m)
    conf = cm.group(1) if cm else None     # legacy threshold classifier emits no probability
    desc = re.sub(r"^Classification:[^.]*\.\s*", "", m)
    desc = re.sub(r"\s*\(Confidence:[^)]*\)\s*", " ", desc).strip()
    return label, conf, desc, raw

def conf_txt(conf):
    return f"{conf} confidence" if conf else "rule-based classifier"

def card_fig(c, color):
    rgba = {"#0B3D91": "rgba(11,61,145,0.09)", "#2BB2A6": "rgba(43,178,166,0.11)"}.get(color, "rgba(0,0,0,0.05)")
    fig = go.Figure(go.Scatter(x=c["position"], y=c["load"], mode="lines",
                               line=dict(color=color, width=2.5), fill="toself", fillcolor=rgba))
    fig.update_layout(title=f"Dynamometer card — {parse(c['diagnostic_message'])[0]}",
                      height=360, template="plotly_white",
                      xaxis_title="Rod position (in)", yaxis_title="Load (lbs)", margin=dict(t=54))
    return fig

CARDS = pathlib.Path(__file__).parent / "dynacard-cards"
def _card(*names):
    for n in names:
        if pathlib.Path(n).exists(): return json.load(open(n))
    raise SystemExit(f"no card found ({names})")
def compose(out, card2=None):
    cards = [_card(CARDS/"pt-card.json", "/tmp/pt-card.json"),
             _card(card2) if card2 else _card(CARDS/"fp-card.json", "/tmp/fp-card-721.json")]
    b = GTMReportBuilder(title="Rod-Pump Dynamometer Card Diagnostics",
                         subtitle="Sucker-rod pump fault diagnosis · digitalmodel artificial_lift",
                         demo_id="dynacard_diagnostics", case_count=2,
                         code_refs=["digitalmodel artificial_lift.dynacard", "Gibbs wave-equation surface→downhole"])
    b.add_methodology(
        "<p>A surface dynamometer card (rod load vs position over a pump stroke) is converted to the "
        "downhole pump card via the Gibbs wave equation, then classified against rod-pump fault "
        "signatures — pump fillage, card area/shape, and load spikes. Two common conditions are "
        "diagnosed below.</p>")
    b.add_assumptions(["Sucker-rod pump · 1.0 in rod × 5000 ft · 1.75 in pump at 5000 ft · 10 SPM · 144 in stroke",
                       "Surface cards generated by the digitalmodel synthetic-card engine; diagnosed by its default classifier"])
    rows = []
    for c in cards:
        label, conf, desc, raw = parse(c["diagnostic_message"])
        rows.append((label, conf or "rule-based", f"{c['fillage']:.1f}%", "yes" if c.get("buckling_detected") else "no"))
    b.add_table("Diagnoses", pd.DataFrame(rows, columns=["Condition", "Classifier", "Pump fillage", "Rod buckling"]),
                subtitle="Two diagnosed cards")
    for c, color in zip(cards, (NAVY, TEAL)):
        label, conf, desc, raw = parse(c["diagnostic_message"])
        b.add_chart(c["mode"].lower(), card_fig(c, color), f"{label} card", f"{conf_txt(conf)} · fillage {c['fillage']:.1f}%")
        b.add_section(f"{label} — diagnosis", f"<p><strong>{label}</strong> ({conf_txt(conf)}, "
                      f"{c['fillage']:.1f}% pump fillage). {desc}</p>")
    p0, p1 = parse(cards[0]["diagnostic_message"]), parse(cards[1]["diagnostic_message"])
    b.add_section("Verdict",
        "<p>Two distinct rod-pump faults diagnosed from their card signatures: "
        f"<strong>{p0[0]}</strong> ({SIG.get(p0[3], 'characteristic card shape')}, {cards[0]['fillage']:.0f}% fillage) and "
        f"<strong>{p1[0]}</strong> ({SIG.get(p1[3], 'characteristic card shape')}, {cards[1]['fillage']:.0f}% fillage). "
        "Each carries a recommended action so the pump can be restored without a slickline trip.</p>")
    b.build(out)
    html = pathlib.Path(out).read_text()
    html = re.sub(r'<div class="case-badge">.*?</div>',
                  '<div class="case-badge">digitalmodel artificial_lift · automated card diagnosis</div>', html, flags=re.S)
    html = html.replace("parametric analysis", "engineering analysis")
    pathlib.Path(out).write_text(html)
    print(f"composed dynacard (2 diagnoses) -> {out}")

if __name__ == "__main__":
    compose(sys.argv[1], sys.argv[2] if len(sys.argv) > 2 else None)
